SPI1 DMA implementation
electro-smith/libDaisy pull request #359
Opened 2021-06-16 10:41 UTC by brbrr

This is the first config-less iteration on adding DMA support to SPI. This configuration is battle-tested with ILI9341-based 240x320 TFT display. 

I'm opening this PR mostly to gather some feedback on whether it is needed at all and get suggestions on the best way to implement it.

Obviously, DMA init should be configurable similar to SPI. If this PR would make sense, I'll work on adding configuration support as a next step.

2021-06-16 14:37 UTC, TheSlowGrowth commented
I quickly looked into the code. 
- I'm not sure about the DmaFlag() functions, they look like an exposed implementation detail to me.
- Multiple SpiHandles must be able to start DMA transmissions simultaneously without interfering with each other. Right now, you can effectively only use DMA for a single SpiHandle without everything breaking apart.

I think regarding the overall structure, you can take a look at the I2C implementation. There we have a "scheduling" system so that multiple I2CHandles can share a single DMA which will transmit scheduled jobs on these individual handles one after the other. Without this scheduling, you end up with collisions between multiple handles that want to transmit with DMA simultaneously.

2021-06-17 15:41 UTC, brbrr commented
Thanks, @TheSlowGrowth! I followed your suggestion and implemented scheduling similarly (ctrl-c/ctrl-v mostly 😬) to I2C implementation. 

Unfortunately, I running into some sort of a race condition when calling `DmaTransmit` multiple(10) times in a loop. I can't really figure out what's going on, but here is what I discovered so far:

- Only 2 calls out of 10 is being processed, specifically, only first and last one.
- When libDaisy optimizations disabled (`-O3`) all the calls processed in order

2021-06-18 15:03 UTC, TheSlowGrowth requested changes
Here's a couple of things I noticed. I'll be taking a closer look later when I have more time

2021-06-18 15:03 UTC, TheSlowGrowth commented on src/per/spi.cpp
> +    // HAL_DMA_IRQHandler(&spi_handles[0].hdma_spi_);
remember to remove this when you're ready ;-)

2021-06-18 15:03 UTC, TheSlowGrowth commented on src/per/spi.cpp
> +    // SpiHandle::Impl* handle = MapInstanceToHandle(hspi->Instance);
remember to remove this when you're ready ;-)

2021-06-18 15:03 UTC, TheSlowGrowth commented on src/per/spi.cpp
> +SpiHandle::DmaTransmit(uint8_t*                       buff,
You haven't yet added the queue to the DmaReceive function

2021-06-18 15:14 UTC, brbrr commented on src/per/spi.cpp
> +    enum
I think you reviewed outdated revision. I have already done it and moved it into a header file: 
b5bcbb5

2021-07-19 19:41 UTC, brbrr commented
Hey @TheSlowGrowth. I think I addressed all of your feedback

2021-07-21 15:58 UTC, TheSlowGrowth reviewed
Good job it's looking very nice and I don't see anything obvious. I'll try to get this running on some hardware later to see it in action.

2021-08-20 18:17 UTC, brbrr commented
FWIW I was not been able to reproduce the styling issue locally with VSCode and via `clang-fromat` executable installed from brew.

2021-08-24 23:37 UTC, stephenhensley commented
Overall looking very good! Will do some actual testing on the hardware this week, and should be able to get it merged if there are no issues!

2021-09-08 20:51 UTC, stephenhensley commented
@brbrr apologies on the delay here, but we finally found some time to do a bit of hardware testing, and it works!

I think I'm signing off on everything here!

We'll take care of the addition to the changelog for this, but in the future if you could add an entry to the changelog along with your PR that would be great.

Thanks again so much for the contribution!

2021-09-08 20:52 UTC, merged