Report memory usage at the end of the build step (fix #363)
electro-smith/libDaisy pull request #379
Opened 2021-07-10 02:07 UTC by zeroisnan

I added the linker options as discussed in #363

2021-07-12 21:45 UTC, stephenhensley requested changes
@zeroisnan this is great. Thanks for adding this!

I'd say with the linker reporting memory usage we can remove line 231 from the core/Makefile (`$SZ $@`) since it provides a similar, but much less detailed report. I don't see a reason to keep both around.

Also could you add a brief note to the `CHANGELOG.md` file in the "Other" subsection regarding your addition.

Thanks!

2021-07-18 11:15 UTC, zeroisnan commented
Hi @stephenhensley,
happy to help! I have implemented the tweaks you suggested.

The size command is no longer used in the Makefile now, but I left the code settings the path to the command ( $(SZ) variable). Let me know if you want me to remove them as well.

2021-07-19 16:45 UTC, stephenhensley approved these changes

2021-07-19 16:45 UTC, stephenhensley commented
@zeroisnan Thanks! 

Yeah, I'm fine with leaving the `$(SZ)` variable in place anyway. It's nice to have the typical compiler commands added into the top of the Makefile

2021-07-19 16:46 UTC, merged