Bootloader binary incorporation
electro-smith/libDaisy pull request #431
Opened 2021-11-05 18:33 UTC by CorvusPrudens

This adds the pre-built bootloader binary to libDaisy, along with a couple linkers for programs that want to run from the bootloader. We don't have a convenient mechanism for using those linkers at the moment, but I'd rather get them in place now.

2021-11-05 18:38 UTC, CorvusPrudens commented
Ran a quick test to make sure the target works. Looks all good!

2021-11-05 18:38 UTC, CorvusPrudens commented
![](https://github.trello.services/images/mini-trello-icon.png) [add bootloader to libDaisy](https://trello.com/c/DTHLWWuf/316-add-bootloader-to-libdaisy)

2021-11-08 16:28 UTC, stephenhensley requested changes
Looks good other than the one var in the core/Makefile.

2021-11-08 16:28 UTC, stephenhensley commented on core/Makefile
> +BOOT_BIN = $(wildcard $(SYSTEM_FILES_DIR)/dsy_bootloader*)
Let's make this conditionally assigned with `?=` instead.

That'll make testing new version of the bootloader, or relying on older versions of the bootloader a bit easier in the future.

2021-11-08 19:07 UTC, stephenhensley approved these changes

2021-11-08 19:07 UTC, merged