Spi examples
electro-smith/libDaisy pull request #526
Opened 2022-05-19 19:01 UTC by beserge

2022-05-19 23:02 UTC, stephenhensley requested changes
In addition to the specific changes:

* With short intros at the top of each file we can keep the footprint as minimal as possible, and remove the READMEs which just feel a bit cluttery in this environment.
* Seems like changes to our examples/ folder don't trigger build CI (to make sure they build)
  * you just need to edit the `paths:` list in the `build.yml` for this.
  * unfortunately the nested folders aren't going to get checked... so we'll want to fix that in a subsequent update, or just unnest them for now (probably fine since there's only two and most of these should be accessible from guides in libDaisy docs anyway).

At some point we'll want to update the style CI to check the examples as well, but it doesn't like multiple source folders in the `source` parameter of the workflow so that would need to get swapped with `excludes` parameters, and its kind of outside of the scope of this PR.

2022-05-19 23:02 UTC, stephenhensley commented
JK nested examples built just fine!

2022-05-19 23:30 UTC, beserge commented on examples/SPI/SpiDmaTransmit/SpiDmaTransmit.cpp
> +
Yeah this doesn't work. I wrote the documentation before the code, this is one change I forgot to backannotate

2022-05-23 23:29 UTC, stephenhensley approved these changes

2022-05-23 23:29 UTC, merged